### PR TITLE
Add styling to GraphUI

### PR DESCRIPTION
**Pull request by jayeclark**
Signed-off-by: Jay Clark <jay@jayeclark.dev>

Hello there! I was looking for opportunities to practice front-end styling and came across issue #18 and thought I'd make some suggestions on layout and interactivity. (The date values now update when the date selection buttons are clicked, and the button is highlighted as well.)

Happy to adjust the commit to meet your repository preferences (I primarily focused on CSS, with some inline styling where it didn't seem useful to create a class/the styling was unlikely to need to be reused.)

graphui-improvements

### CODE REVIEW

**Comment by mike-shields-dev** [comment]
Hi @jayeclark, this looks great! Thank you very much for your contribution. I like the improvements you have made, however, Isn't using `refs` rather than `id's` deemed good practice in react apps? Is this a concept you are familiar with? I know currently the app is only small and currently the components are unique, but the app may grow and change and the document could end up with multiple elements with the same id's and this might be a problem. I found this article that covers why `refs` are a good idea: https://www.ronaldjamesgroup.com/blog/reason-behind-using-refs-instead-of-id-in-react-js I'm open to hearing your take on this, I'm no expert. :blush:

**Comment by jayeclark** [comment]
Hi, yes, that's correct. A few other things should change as well to make the graphUI a reusable React component, now that I think about it. I can add an additional commit tomorrow fixing those items. Thanks for the feedback!

**Comment by jayeclark** [comment]
@mike-shields-dev I refactored the GraphUI component to use refs, now there should be no issue with the functionality if the component appears multiple times on a page. Also made it easier to add additional date filter buttons in the future (for example, if you wanted to add a 'Last 14 Days' button, it would simply need to be added to the buttons array declared on lines 57 - 59.)

**Review by mike-shields-dev — APPROVED** [review]
Hi @jayeclark, thanks for this contribution, it's very much appreciated 👍

**Pull request merged**
